name: octoconda

on:
  workflow_dispatch:
    inputs:
      configFile:
        description: Configuration file
        default: "config.toml"
        type: string
      workDir:
        description: work directory
        default: "./work_dir"
        type: string
      filter:
        description: Regex filter for repositories (overrides the matrix split)
        type: string
  schedule:
    - cron: "4 0,4,8,10,12,14,16,18,20 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read # read the contents of the repository
  repository-projects: read # read release details
  id-token: write # trusted publishing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build octoconda
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: octoconda-binary
          path: target/release/octoconda

  sync-packages:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # include:
        #   - name: "a"
        #     filter: "(?i)^a"
        #   - name: "b"
        #     filter: "(?i)^b"
        #   - name: "c"
        #     filter: "(?i)^c"
        #   - name: "d"
        #     filter: "(?i)^d"
        #   - name: "e"
        #     filter: "(?i)^e"
        #   - name: "f"
        #     filter: "(?i)^f"
        #   - name: "g"
        #     filter: "(?i)^g"
        #   - name: "h"
        #     filter: "(?i)^h"
        #   - name: "i-j"
        #     filter: "(?i)^[ij]"
        #   - name: "k"
        #     filter: "(?i)^k"
        #   - name: "l"
        #     filter: "(?i)^l"
        #   - name: "m"
        #     filter: "(?i)^m"
        #   - name: "n"
        #     filter: "(?i)^n"
        #   - name: "o"
        #     filter: "(?i)^o"
        #   - name: "p-q"
        #     filter: "(?i)^[pq]"
        #   - name: "r"
        #     filter: "(?i)^r"
        #   - name: "s"
        #     filter: "(?i)^s"
        #   - name: "t"
        #     filter: "(?i)^t"
        #   - name: "u-v"
        #     filter: "(?i)^[uv]"
        #   - name: "w-z"
        #     filter: "(?i)^[w-z0-9]"
        include:
          - name: "all"
            filter: "(?i)^."

    env:
      CONFIG_FILE: ${{ github.event.inputs.configFile || 'config.toml' }}
      WORK_DIR: ${{ github.event.inputs.workDir || './work_dir' }}
      FILTER: ${{ github.event.inputs.filter || matrix.filter }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Download octoconda binary
        uses: actions/download-artifact@v4
        with:
          name: octoconda-binary

      - name: Make binary executable
        run: chmod +x octoconda

      - name: Install rattler-build (binary)
        run: |
          mkdir bin
          curl -L -o bin/rattler-build "https://github.com/prefix-dev/rattler-build/releases/latest/download/rattler-build-x86_64-unknown-linux-musl"
          chmod +x bin/rattler-build
          file bin/rattler-build
        shell: bash

      - name: Run octoconda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./octoconda "--work-dir=${{ env.WORK_DIR }}" "--config-file=${{ env.CONFIG_FILE }}" "--filter=${FILTER}"

      - name: Build and upload packages
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/package_and_upload_all.sh" \
            && (\
              cd "${GITHUB_WORKSPACE}" \
              && cd "${{ env.WORK_DIR }}" \
              && PATH="${GITHUB_WORKSPACE}/bin:${PATH}" "${GITHUB_WORKSPACE}/scripts/package_and_upload_all.sh" \
            )

      - name: Add Job Summary
        if: always()
        run: |
          { \
            echo "# Octoconda Report (${{ matrix.name }})"; \
            echo; \
          } >> "$GITHUB_STEP_SUMMARY"

          if test -f "${{ env.WORK_DIR }}/report.txt"; then
            cat "${{ env.WORK_DIR }}/report.txt" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "*no report available*" >> "$GITHUB_STEP_SUMMARY"
          fi

          { \
            echo "# Summary"; \
            echo; \
          } >> "$GITHUB_STEP_SUMMARY"

          if test -f "${{ env.WORK_DIR }}/status.txt"; then
            cat "${{ env.WORK_DIR }}/status.txt" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "*no status available*" >> "$GITHUB_STEP_SUMMARY"
          fi
